# Generated by Django 4.2 on 2024-08-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_ingredient_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('quantity_uom', models.CharField(default='grams', max_length=255)),
                ('expiration_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantry.food')),
            ],
        ),
        migrations.RemoveField(
            model_name='nutrientvalue',
            name='food',
        ),
        migrations.RemoveField(
            model_name='nutrientvalue',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_uom',
            field=models.CharField(default='grams', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='pantry.ingredient'),
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
        migrations.DeleteModel(
            name='NutrientValue',
        ),
    ]
