# Generated by Django 4.2 on 2024-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_remove_ingredient_unit_alter_ingredient_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='foodinventory',
            options={'verbose_name_plural': 'Food Inventories'},
        ),
        migrations.AlterField(
            model_name='foodinventory',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='foodinventory',
            name='quantity_uom',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('cup', 'cups')], default='g', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='pantry.tag'),
        ),
    ]
