# Generated by Django 4.2 on 2024-08-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_tag_alter_foodinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
