# Generated by Django 4.2 on 2024-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_alter_foodinventory_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinventory',
            name='quantity_uom',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons'), ('cup', 'cups'), ('pcs', 'pieces')], default='g', max_length=255),
        ),
    ]
